package com.noorheroes.car24assignment.core.designsystem.token

import kotlinx.serialization.Serializable

@Serializable
enum class ColorToken {
    PRIMARY, ON_PRIMARY, PRIMARY_CONTAINER, ON_PRIMARY_CONTAINER,
    SECONDARY, ON_SECONDARY, SECONDARY_CONTAINER, ON_SECONDARY_CONTAINER,
    TERTIARY, ON_TERTIARY, TERTIARY_CONTAINER, ON_TERTIARY_CONTAINER,
    BACKGROUND, ON_BACKGROUND, SURFACE, ON_SURFACE,
    SURFACE_VARIANT, ON_SURFACE_VARIANT, OUTLINE, OUTLINE_VARIANT,
    ERROR, ON_ERROR, ERROR_CONTAINER, ON_ERROR_CONTAINER,
    SUCCESS, ON_SUCCESS, WARNING, ON_WARNING, INFO, ON_INFO,
    TRANSPARENT, BLACK, WHITE
}
